/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookHome: typeof import('./src/components/BookHome.vue')['default']
    BookItem: typeof import('./src/components/BookItem.vue')['default']
    BookItemList: typeof import('./src/components/BookItemList.vue')['default']
    BookItemTable: typeof import('./src/components/BookItemTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
  }
}
